spring.application.name=notification-service
server.port=8081

spring.security.user.name=admin
spring.security.user.password=admin123

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/dayFlowMar03
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# GROQ
groq.api.key=${GROQ_API_KEY}

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}

# MSG91
sms.auth.key=${MSG91_AUTH_KEY}
sms.sender.id=PhoneMessage
sms.route=4